#!/bin/bash

# Print the account-specific hand-off from AWS/Terraform to Snowflake.
# This is intentionally a small executable checklist rather than a parser for
# docs/E2E_SETUP.md, so formatting changes in the documentation cannot break
# the deploy output.

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"
# shellcheck disable=SC1091
source "$SCRIPTS_DIR/project_config.sh"

INFRA_DIR="$PROJECT_ROOT/infra"

terraform_output() {
    terraform -chdir="$INFRA_DIR" output -raw "$1"
}

AWS_ACCOUNT_ID="$(terraform_output aws_account_id)"
S3_BUCKET="$(terraform_output glue_data_bucket_name)"
GLUE_DATABASE="$(terraform_output glue_catalog_database_name)"
S3_ROLE_ARN="$(terraform_output snowflake_raw_iceberg_s3_role_arn)"
CATALOG_ROLE_ARN="$(terraform_output snowflake_raw_iceberg_catalog_role_arn)"
PII_POC_JOB="$(terraform_output glue_pii_property_poc_job_name)"

echo ""
echo "======================================================================"
echo "✅ AWS infrastructure provisioned successfully"
echo "======================================================================"
echo "Account       : $AWS_ACCOUNT_ID"
echo "AWS profile   : $AWS_PROFILE"
echo "AWS region    : $AWS_REGION"
echo "Data bucket   : $S3_BUCKET"
echo "Glue database : $GLUE_DATABASE"
echo "PII POC job   : $PII_POC_JOB"
echo ""
echo "Created and managed by Terraform:"
echo "  • S3 data bucket and raw-iceberg location"
echo "  • Glue Catalog database and IAM policies"
echo "  • Snowflake S3 role:     $S3_ROLE_ARN"
echo "  • Snowflake Glue role:   $CATALOG_ROLE_ARN"
echo "  • Athena and the enabled optional AWS resources"
echo ""
echo "======================================================================"
echo "Next steps — continue in this order"
echo "======================================================================"
echo "IMPORTANT: Do NOT select and run the entire .local.sql file at once."
echo "The DESC statements are checkpoints: Snowflake returns values there that"
echo "must be copied into AWS IAM before you continue with the next section."
echo ""
echo "1) Upload the Glue code:"
echo "     menu → 3) Upload Glue Scripts to S3"
echo ""
echo "2) Generate the account-specific Snowflake SQL:"
echo "     menu → 7) Generate Snowflake SQL"
echo "     Then open the generated snowflake/*.local.sql files."
echo ""
echo "3) Create the Glue Iceberg tables:"
echo "     menu → 6) Run Glue Pipelines → 1"
echo "     For the table-property PII POC, also run submenu option 5."
echo ""
echo "4) In Snowflake, open:"
echo "     snowflake/raw_iceberg_linked_database.local.sql"
echo "   Run only the session-context and external-volume statements, then run"
echo "   DESC EXTERNAL VOLUME and STOP. Do not run the whole file."
echo "   Copy these values from the DESC result:"
echo "     STORAGE_AWS_IAM_USER_ARN"
echo "     STORAGE_AWS_EXTERNAL_ID"
echo "   In AWS IAM, update this role's trust policy:"
echo "     $S3_ROLE_ARN"
echo "   Set Principal.AWS directly to STORAGE_AWS_IAM_USER_ARN. Do not use"
echo "   arn:aws:iam::$AWS_ACCOUNT_ID:root and do not add aws:PrincipalArn."
echo "   Set sts:ExternalId to STORAGE_AWS_EXTERNAL_ID. Then return to Snowflake"
echo "   and run: SELECT SYSTEM\$VERIFY_EXTERNAL_VOLUME('GLUE_RAW_ICEBERG_VOLUME');"
echo ""
echo "5) Continue only after the external volume verification succeeds."
echo "   Run CREATE CATALOG INTEGRATION, then DESC CATALOG INTEGRATION and STOP."
echo "   If the integration already exists, do not run CREATE again; run DESC only."
echo "   Copy these values from the DESC result:"
echo "     GLUE_AWS_IAM_USER_ARN"
echo "     GLUE_AWS_EXTERNAL_ID"
echo "   In AWS IAM, update this different role's trust policy:"
echo "     $CATALOG_ROLE_ARN"
echo "   Set Principal.AWS directly to GLUE_AWS_IAM_USER_ARN. Do not use"
echo "   arn:aws:iam::$AWS_ACCOUNT_ID:root and do not use STORAGE_AWS_* values."
echo "   Set sts:ExternalId to GLUE_AWS_EXTERNAL_ID. Then return to Snowflake"
echo "   and continue with the GRANT statements and linked-database section."
echo "   Do not check catalog-link status until the linked database exists."
echo ""
echo "6) Create the linked database only after both trust policies are updated."
echo "   Run the linked-database CREATE DATABASE section as SYSADMIN. Then check:"
echo "     SHOW SCHEMAS IN DATABASE GLUE_RAW_ICEBERG;"
echo "     SHOW TABLES IN SCHEMA GLUE_RAW_ICEBERG.\"$GLUE_DATABASE\";"
echo "     SELECT SYSTEM\$CATALOG_LINK_STATUS('GLUE_RAW_ICEBERG');"
echo "   RUNNING means discovery is scheduled or in progress; it does not"
echo "   guarantee that all tables are visible yet. Refresh after the sync."
echo "   If the schema remains empty, run ALTER DATABASE ... RESUME DISCOVERY"
echo "   and verify that the expected tables exist in the AWS Glue database."
echo ""
echo "If you already ran the entire SQL file: do not start over."
echo "  • Re-run DESC EXTERNAL VOLUME and fix the S3 role trust policy."
echo "  • Re-run DESC CATALOG INTEGRATION and fix the catalog role trust policy."
echo "  • Keep existing Snowflake objects; CREATE already-exists errors are expected."
echo "  • Check the linked-database status again after both trust fixes."
echo ""
echo "7) After the linked database is healthy:"
echo "   • Run setup_glue_raw_iceberg_roles_and_masking.local.sql for the"
echo "     existing description-based PII flow."
echo "   • If the PII property POC was run, execute"
echo "     setup_iceberg_property_pii_poc.local.sql."
echo "     That file has one additional DESC STORAGE INTEGRATION pause;"
echo "     add its returned trust statement to the S3 role above."
echo ""
echo "No manual AWS policy attachment is required: Terraform manages the"
echo "Snowflake-role permission policies. Only the Snowflake-generated trust"
echo "values must be added to the IAM trust relationships."
echo ""
echo "Full procedure: $PROJECT_ROOT/docs/E2E_SETUP.md"
echo "======================================================================"
