#!/bin/bash

# Print the account-specific hand-off from AWS/Terraform to Snowflake.
# This is intentionally a small executable checklist rather than a parser for
# docs/E2E_SETUP.md, so formatting changes in the documentation cannot break
# the deploy output.

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"
# shellcheck disable=SC1091
source "$SCRIPTS_DIR/project_config.sh"

INFRA_DIR="$PROJECT_ROOT/infra"

terraform_output() {
    terraform -chdir="$INFRA_DIR" output -raw "$1"
}

AWS_ACCOUNT_ID="$(terraform_output aws_account_id)"
S3_BUCKET="$(terraform_output glue_data_bucket_name)"
GLUE_DATABASE="$(terraform_output glue_catalog_database_name)"
S3_ROLE_ARN="$(terraform_output snowflake_raw_iceberg_s3_role_arn)"
CATALOG_ROLE_ARN="$(terraform_output snowflake_raw_iceberg_catalog_role_arn)"
PII_POC_JOB="$(terraform_output glue_pii_property_poc_job_name)"

echo ""
echo "======================================================================"
echo "✅ AWS infrastructure provisioned successfully"
echo "======================================================================"
echo "Account       : $AWS_ACCOUNT_ID"
echo "AWS profile   : $AWS_PROFILE"
echo "AWS region    : $AWS_REGION"
echo "Data bucket   : $S3_BUCKET"
echo "Glue database : $GLUE_DATABASE"
echo "PII POC job   : $PII_POC_JOB"
echo ""
echo "Created and managed by Terraform:"
echo "  • S3 data bucket and raw-iceberg location"
echo "  • Glue Catalog database and IAM policies"
echo "  • Snowflake S3 role:     $S3_ROLE_ARN"
echo "  • Snowflake Glue role:   $CATALOG_ROLE_ARN"
echo "  • Athena and the enabled optional AWS resources"
echo ""
echo "======================================================================"
echo "Next steps — continue in this order"
echo "======================================================================"
echo "1) Upload the Glue code:"
echo "     menu → 3) Upload Glue Scripts to S3"
echo ""
echo "2) Generate the account-specific Snowflake SQL:"
echo "     menu → 7) Generate Snowflake SQL"
echo "     Then open the generated snowflake/*.local.sql files."
echo ""
echo "3) Create the Glue Iceberg tables:"
echo "     menu → 6) Run Glue Pipelines → 1"
echo "     For the table-property PII POC, also run submenu option 5."
echo ""
echo "4) In Snowflake, open:"
echo "     snowflake/raw_iceberg_linked_database.local.sql"
echo "   Run the external-volume section through DESC EXTERNAL VOLUME."
echo "   In AWS IAM, update this role's trust policy:"
echo "     $S3_ROLE_ARN"
echo "   Use the returned values exactly as follows:"
echo "     Principal.AWS = STORAGE_AWS_IAM_USER_ARN"
echo "     sts:ExternalId = STORAGE_AWS_EXTERNAL_ID"
echo "   Then return to Snowflake and run SYSTEM\$VERIFY_EXTERNAL_VOLUME."
echo ""
echo "5) Continue the same Snowflake file through DESC CATALOG INTEGRATION."
echo "   In AWS IAM, update this different role's trust policy:"
echo "     $CATALOG_ROLE_ARN"
echo "   Use the returned values exactly as follows:"
echo "     Principal.AWS = GLUE_AWS_IAM_USER_ARN"
echo "     sts:ExternalId = GLUE_AWS_EXTERNAL_ID"
echo "   Then return to Snowflake and finish creating the linked database."
echo ""
echo "6) After the linked database is healthy:"
echo "   • Run setup_glue_raw_iceberg_roles_and_masking.local.sql for the"
echo "     existing description-based PII flow."
echo "   • If the PII property POC was run, execute"
echo "     setup_iceberg_property_pii_poc.local.sql."
echo "     That file has one additional DESC STORAGE INTEGRATION pause;"
echo "     add its returned trust statement to the S3 role above."
echo ""
echo "No manual AWS policy attachment is required: Terraform manages the"
echo "Snowflake-role permission policies. Only the Snowflake-generated trust"
echo "values must be added to the IAM trust relationships."
echo ""
echo "Full procedure: $PROJECT_ROOT/docs/E2E_SETUP.md"
echo "======================================================================"
