#!/bin/bash

# Print the account-specific hand-off from AWS/Terraform to Snowflake.
# This is intentionally a small executable checklist rather than a parser for
# docs/E2E_SETUP.md, so formatting changes in the documentation cannot break
# the deploy output.

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"
# shellcheck disable=SC1091
source "$SCRIPTS_DIR/project_config.sh"

INFRA_DIR="$PROJECT_ROOT/infra"

terraform_output() {
    terraform -chdir="$INFRA_DIR" output -raw "$1"
}

AWS_ACCOUNT_ID="$(terraform_output aws_account_id)"
AWS_REGION="$(terraform_output glue_data_bucket_region)"
S3_BUCKET="$(terraform_output glue_data_bucket_name)"
GLUE_DATABASE="$(terraform_output glue_catalog_database_name)"
S3_ROLE_ARN="$(terraform_output snowflake_raw_iceberg_s3_role_arn)"
CATALOG_ROLE_ARN="$(terraform_output snowflake_raw_iceberg_catalog_role_arn)"
SNOWFLAKE_EXTERNAL_VOLUME_NAME="$(terraform_output snowflake_raw_iceberg_external_volume_name)"
SNOWFLAKE_CATALOG_INTEGRATION_NAME="$(terraform_output snowflake_raw_iceberg_catalog_integration_name)"
SNOWFLAKE_LINKED_DATABASE_NAME="$(terraform_output snowflake_raw_iceberg_linked_database_name)"
PII_POC_JOB="$(terraform_output glue_pii_property_poc_job_name)"
COMPLEX_TYPES_POC_JOB="$(terraform_output glue_complex_types_poc_job_name)"

echo ""
echo "======================================================================"
echo "✅ AWS infrastructure provisioned successfully"
echo "======================================================================"
echo "Account       : $AWS_ACCOUNT_ID"
echo "AWS profile   : $AWS_PROFILE"
echo "AWS region    : $AWS_REGION"
echo "Data bucket   : $S3_BUCKET"
echo "Glue database : $GLUE_DATABASE"
echo "PII POC job   : $PII_POC_JOB"
echo "Complex types : $COMPLEX_TYPES_POC_JOB"
echo ""
echo "Created and managed by Terraform:"
echo "  • S3 data bucket and raw-iceberg location"
echo "  • Glue Catalog database and IAM policies"
echo "  • Snowflake S3 role:     $S3_ROLE_ARN"
echo "  • Snowflake Glue role:   $CATALOG_ROLE_ARN"
echo "  • Athena and the enabled optional AWS resources"
echo ""
echo "======================================================================"
echo "Next steps — continue in this order"
echo "======================================================================"
echo "IMPORTANT: Do NOT select and run the entire .local.sql file at once."
echo "The DESC statements are checkpoints: Snowflake returns values there that"
echo "must be copied into AWS IAM before you continue with the next section."
echo ""
echo "1) Upload the Glue code:"
echo "     menu → 3) Upload Glue Scripts to S3"
echo ""
echo "2) Generate the account-specific Snowflake SQL:"
echo "     menu → 7) Generate Snowflake SQL"
echo "     Then open snowflake/setup_raw_iceberg.local.sql."
echo ""
echo "3) Set up the universal Snowflake raw Iceberg link first:"
echo "     Open snowflake/setup_raw_iceberg.local.sql."
echo "     Run section 1, DESC EXTERNAL VOLUME, then STOP."
echo "     Update this AWS IAM role's Trust relationship:"
echo "       $S3_ROLE_ARN"
echo "     Terraform output: snowflake_raw_iceberg_s3_role_arn"
echo "       terraform -chdir=infra output snowflake_raw_iceberg_s3_role_arn"
echo "     Use STORAGE_AWS_IAM_USER_ARN as Principal.AWS and"
echo "     STORAGE_AWS_EXTERNAL_ID as sts:ExternalId."
echo "     Do not update the catalog role at this checkpoint."
echo "     Run section 2 and VERIFY_EXTERNAL_VOLUME on $SNOWFLAKE_EXTERNAL_VOLUME_NAME;"
echo "     continue only when"
echo "     awsRoleArnValidationResult is PASSED."
echo "     Run section 3, DESC CATALOG INTEGRATION, then STOP."
echo "     Update this different AWS IAM role's Trust relationship:"
echo "       $CATALOG_ROLE_ARN"
echo "     Terraform output: snowflake_raw_iceberg_catalog_role_arn"
echo "       terraform -chdir=infra output snowflake_raw_iceberg_catalog_role_arn"
echo "     Use API_AWS_IAM_USER_ARN as Principal.AWS and"
echo "     API_AWS_EXTERNAL_ID as sts:ExternalId."
echo "     Do not reuse the STORAGE_AWS_* values here."
echo "     Run section 4 to create $SNOWFLAKE_LINKED_DATABASE_NAME."
echo "     Check the link status and discovery output in section 5:"
echo "       SHOW SCHEMAS IN DATABASE $SNOWFLAKE_LINKED_DATABASE_NAME;"
echo "       SHOW TABLES IN SCHEMA $SNOWFLAKE_LINKED_DATABASE_NAME.\"$GLUE_DATABASE\";"
echo "       SELECT SYSTEM\$CATALOG_LINK_STATUS('$SNOWFLAKE_LINKED_DATABASE_NAME');"
echo "     RUNNING means discovery is scheduled/in progress; refresh after sync."
echo "     If the schema stays empty, run ALTER DATABASE ... RESUME DISCOVERY."
echo ""
echo "4) Create any desired Glue Iceberg tables:"
echo "     menu → 6) Run Glue Pipelines"
echo "     Choose option 1 for the standard tables, option 5 for the"
echo "     table-property PII POC, or option 6 for complex types."
echo "   All tables in the Terraform Glue database and raw-iceberg/ prefix"
echo "   are discovered through the same $SNOWFLAKE_LINKED_DATABASE_NAME database."
echo ""
echo "5) Trust-policy value mapping, if you need to re-check it:"
echo "   External volume $SNOWFLAKE_EXTERNAL_VOLUME_NAME → role $S3_ROLE_ARN"
echo "     STORAGE_AWS_IAM_USER_ARN → Principal.AWS"
echo "     STORAGE_AWS_EXTERNAL_ID  → sts:ExternalId"
echo "   Catalog integration $SNOWFLAKE_CATALOG_INTEGRATION_NAME → role $CATALOG_ROLE_ARN"
echo "     API_AWS_IAM_USER_ARN    → Principal.AWS"
echo "     API_AWS_EXTERNAL_ID     → sts:ExternalId"
echo "   Use the returned Snowflake IAM user directly. Do not use the AWS root,"
echo "   aws:PrincipalArn, or the SNOWFLAKE_TRUST_NOT_CONFIGURED placeholder."
echo ""
echo "6) After the linked database is healthy and tables are visible:"
echo "   • Run setup_glue_raw_iceberg_roles_and_masking.local.sql for the"
echo "     reusable roles, tags and scalar/MAP/ARRAY/VARIANT masking policies."
echo "   • Apply column-level PII tags with the metadata-driven association"
echo "     flow after reviewing pii_column_metadata."
echo "   • Run setup_dynamic_object_pii_masking.local.sql for PII OBJECT"
echo "     columns whose structured schema is discovered from Snowflake."
echo "     It creates column-specific policies and never executes UNSET or DROP."
echo "   • If the PII property POC was run, execute"
echo "     setup_iceberg_property_pii_poc.local.sql."
echo "     That file has one additional DESC STORAGE INTEGRATION pause;"
echo "     add its returned trust statement to the S3 role above."
echo ""
echo "If you already ran the entire SQL file: do not start over."
echo "  • Re-run DESC EXTERNAL VOLUME and fix the S3 role trust policy."
echo "  • Re-run DESC CATALOG INTEGRATION and fix the catalog role trust policy."
echo "  • Keep existing Snowflake objects; CREATE already-exists errors are expected."
echo "  • Check the linked-database status again after both trust fixes."
echo ""
echo "No manual AWS policy attachment is required: Terraform manages the"
echo "Snowflake-role permission policies. Only the Snowflake-generated trust"
echo "values must be added to the IAM trust relationships."
echo ""
echo "Full procedure: $PROJECT_ROOT/docs/E2E_SETUP.md"
echo "======================================================================"
